### ISSUE TITLE
Make the library usable on UWP (Windows Apps)

### ISSUE THREAD

**Issue by M-WOLF** [wis3guy/HalClient.Net#16]
Would be great to share code between WinForm, Wpf and UWP

**Comment by wis3guy** [comment]
I am unsure what that would entail as i do not do UWP development. Could you elaborate?

**Comment by zijianhuang** [comment]
It should be easy, even though I don't do UWP development either. Have a look at my WebApiClientGen project at https://github.com/zijianhuang/webapiclientgen you may get some hints.

**Comment by wis3guy** [comment]
A PCL version is now available which requires netstandard1.1. As can be read here https://docs.microsoft.com/en-us/dotnet/standard/library you should be able to reference it from UWP projects.

To use it, update your package to 3.0.0.
