### ISSUE TITLE
No 'ApiRootResourceCachingBehavior' option on IHalHttpClientConfiguration 

### ISSUE THREAD

**Issue by Not-That-Guy** [wis3guy/HalClient.Net#17]
Documentation talks about a  'ApiRootResourceCachingBehavior' option to configure all IHalHttpClient instances, but I can't actually set this option in code.

Nothing on the class HalHttpClientConfiguration matching this option. Searching the source and it only turns up in the readme document.

I assume this is redundant and the caching is configured: 
`using (var client = await factory.CreateClientAsync(CachingBehavior.PerClient))
{
	// client.CachedApiRootResource is set to a parsed IRootResourceObject instance
}`

**Comment by wis3guy** [comment]
@Not-That-Guy You are absolutely correct. The documentation was out of sync with the source code. Realize that the caching of the root resource is something to be handled by the factory and was thus removed form the client specific configuration class in favor of the factory method's argument.
