### ISSUE TITLE
Extend JsonSerializer with features in HalJsonParser to HalJsonSerializer

### ISSUE THREAD

**Issue by zijianhuang** [wis3guy/HalClient.Net#19]
so it may be possible to have a high level POCO describing a HAL object. so I may be writing:
```c#
                    using (JsonReader jsonReader = new JsonTextReader(new System.IO.StreamReader(stream)))
                    {
                        var serializer = new HalJsonSerializer();
                        var billerInfo = serializer.Deserialize<LPBillerInfo>(jsonReader);
                        
                    }
```

**Comment by wis3guy** [comment]
To be honest i do not see how this would improve the library, which is a lightweight wrapper for dealing with HAL responses in a **generic manner**. We expose one, and only one, object model representation of a HAL response.

Serialization is not part of the client, as it only consumes HAL responses, it does not produce HAL responses. What you request sounds like a server side component. Consider using (parts of) this project for you serialization needs: https://github.com/JakeGinnivan/WebApi.Hal 

If you want to receive POCO objects from the client, i would suggest you write some extension methods that map an `IHalHttpResponseMessage` instance to your own object model.

**Comment by zijianhuang** [comment]
agree on your analysis and respect your scope of this lib. Currently I am doing C# client programming rather than Web front end programming which is scheduled later. I prefer using strongly typed data when doing app programming. And I had actually used Newtonsoft.Json to deserialize the state object, though parsing the same response is not so ideal. Nevertheless, I see that current HAL schema is not friendly to deseralizing the whole JSON content since HAL was not designed for this.
