### ISSUE TITLE
Moving to 4.0

### ISSUE THREAD

**Issue by gjorchard** [wis3guy/HalClient.Net#25]
I am having some issues between a web service running in Java on a Linux platform and my .NET client. I noticed that release 4.0 has changes for cross platform so I would like to move to the latest. When I tried to upgrade using NuGet I get an error saying that library does not support .NET 4.5.2, though it does not say what is supported. I am not sure where to look to find out what the dependencies are the library. I did see versions for Newtonsoft.Json, System.Net.Http and Tavis.UriTemplates in the HalClient.Net.nuspec though it says its version is 3.1, not 4.0. Guessing this doesn't matter.

My issue is that when I have objects with embedded objects, such as:

public class abc
{
   public string name { get; set; }
   public AnotherObject somefield { get; set; }
}

The "somefield" does not get serialized or deserialized properly. When I say this I mean that the client is not compatible with the web service. Not sure where the actual issue lies. Is this caused by my not using the library correctly?

**Comment by wis3guy** [comment]
@gjorchard Is this still an issue? If not, than please close the issue.

**Comment by gjorchard** [comment]
Problem is long gone. I don't recall what the issue turned out to be. I have closed it.

    On Saturday, January 12, 2019, 6:14:54 a.m. EST, Geoffrey Braaf <notifications@github.com> wrote:  
 
 
@gjorchard Is this still an issue? If not, than please close the issue.
