### ISSUE TITLE
Response parsing loses DateTime UTC info

### ISSUE THREAD

**Issue by lm7777** [wis3guy/HalClient.Net#27]
https://github.com/wis3guy/HalClient.Net/blob/322b45180d24d8de38c29aa3126131c2822bf272/HalClient.Net/Parser/HalJsonParser.cs#L68

If property is of type `DateTime` it loses all possible UTC formatting info during parsing phase.

**Comment by wis3guy** [comment]
How do you suggest we counter the issue? Could you also provide a failing test to reproduce the issue?

**Comment by lm7777** [comment]
Sure. BTW my running env. is .NET Core 2.2
```c#
    [Test]
    public void HalJsonParser_UTC_Bug()
    {
        var parser = new HalJsonParser();
        var utcDateStr = "2019-04-22T20:52:50Z";
        var json = $"{{'date': '{utcDateStr}'}}";
        var result = parser.Parse(json);
        var date = result.StateValues.Single(sv => sv.Name == "date");

        // this fails - parsed value is '2019-04-22 20:52:50'
        Assert.AreEqual(date.Value, utcDateStr);
    }
```
