### ISSUE TITLE
Need access to message details on errors

### ISSUE THREAD

**Issue by gjorchard** [wis3guy/HalClient.Net#4]
The web service I am integrating with provides details of issues in the body of the response where there is an error. This information is not being propagated to the Application by HalClient.

Below is an example of an error message sent by the web service. In this case the developerMessage, errorCode and userMessage would all be useful to have at the application level.

HTTP/1.1 404 Not Found
Date: Mon, 19 Oct 2015 15:03:19 GMT
Content-Type: application/hal+json
Content-Length: 415
Server: Silhouette API v1; Silhouette 7.2
Expires: Tue, 03 Jul 2001 06:00:00 GMT
Cache-Control: no-store, no-cache, must-revalidate, max-age=0
Cache-Control: post-check=0, pre-check=0
Pragma: no-cache

{
  "_links" : {
    "curies" : {
      "href" : "/api/rels/{rel}",
      "name" : "api",
      "templated" : true
    },
    "api:about" : {
      "href" : "/api/v1/events/subscriptions/ws/02bfbaf9-3837-4838-9f9c-307dfb5de8f2/subscriptionsets"
    }
  },
  "developerMessage" : "Requested data or service not exist",
  "errorCode" : "SE1001",
  "httpCode" : 404,
  "userMessage" : "Requested data does not exist"
}

**Comment by wis3guy** [comment]
I understand what you are trying to accomplish/want. Right now i only parse the response upon success (HTTP200). What i should do instead is see what the Content-Type of the response is, and always parse the response in case it is "application/hal+json".

**Comment by gjorchard** [comment]
That sounds good. How would you make the data available to the application?

**Comment by wis3guy** [comment]
This has now been implemented as documented on the project's homepage. The properties of the error message will be treated as any property on a resource.

**Comment by wis3guy** [comment]
I have given this some more thougth over the weekend, and in retrospect i feel that the solution i implemented is not ideal. Rather than always returning a response, and augmenting the returned `IRootResourceObject` instance with the HTTP status code, the client should throw a dedicated exception, which has a property of type `IRootResourceObject`. That way, we adhere to the common programming model, where errors result in exceptions you can `catch` and accordingly deal with in your consuming code.

**Comment by gjorchard** [comment]
That is how I had thought you would implement it, but I was happy with either approach.

**Comment by wis3guy** [comment]
The revised version has now been pushed to nuget.

**Comment by wis3guy** [comment]
Just to inform you that i have rewritten the documentation. There is now also a section describing recommended error handling: https://github.com/wis3guy/HalClient.Net#error-handling
